site_name: Pathware Docs
theme:
  name: material
  features: 
    - instant
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  logo: images/favicon.png
nav:
  - Overview: ./pages/overview/executive_summary.md
  - The Problem: 
    - Page 1.1
    - Page 1.2
    - Page 1.3
  - The Market:
    - Page 2.1
    - Page 2.2
    - Page 2.3
  - The Product:
    - Image Capture Module:
      - Imaging: ./pages/sci-tech/fpm.md
      - Analytics
      - Design
    - Cloud Services: ./pages/sci-tech/cloud-services.md
    - PhaseStain: ./pages/sci-tech/digital-stain.md
  - The Team:
    - Page 4.1
    - Page 4.2
    - Page 4.3
  - Invest: ./pages/invest/detailed_ask_and_use.md
markdown_extensions:
  - admonition